[package]
name = "jj_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "jj_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.41"
jj-cli = "0.31.0"
jj-lib = "0.31.0"
rustler = { version = "0.36.2", features = ["serde"] }
serde = "1.0.219"
